"""Initial client model

Revision ID: ac59ae03c726
Revises:
Create Date: 2025-11-28 19:58:49.535557.
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ac59ae03c726"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
